### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.solr.client.solrj.request.UpdateRequest.setCommitWithin

### ISSUE THREAD

**Issue by AceHack** [inoio/solrs#62]
I get the following error trying to use 2_11 2.1.0.

java.lang.NoSuchMethodError: org.apache.solr.client.solrj.request.UpdateRequest.setCommitWithin(I)V
   at io.ino.solrs.AsyncSolrClient.updateRequest(AsyncSolrClient.scala:242)
   at io.ino.solrs.AsyncSolrClient.addDocs(AsyncSolrClient.scala:301)
   at content.util.solr.SolrIngestor$$anonfun$ingest$1$$anonfun$apply$1.apply(SolrIngestor.scala:29)
   at content.util.solr.SolrIngestor$$anonfun$ingest$1$$anonfun$apply$1.apply(SolrIngestor.scala:19)
   at content.util.timer$.apply(timer.scala:6)
   at content.util.solr.SolrIngestor$$anonfun$ingest$1.apply(SolrIngestor.scala:19)
   at content.util.solr.SolrIngestor$$anonfun$ingest$1.apply(SolrIngestor.scala:18)
   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
   at content.util.solr.SolrIngestor$.ingest(SolrIngestor.scala:18)
   at content.util.SparkRunner$$anonfun$processPartition$1.apply$mcV$sp(SparkRunner.scala:37)
   at content.util.SparkRunner$$anonfun$processPartition$1.apply(SparkRunner.scala:33)
   at content.util.SparkRunner$$anonfun$processPartition$1.apply(SparkRunner.scala:33)
   at content.util.timer$.apply(timer.scala:6)
   at content.util.SparkRunner.processPartition(SparkRunner.scala:33)
   at content.parquet.ContentIngestionJob$$anonfun$reingest$1$$anonfun$apply$mcV$sp$1.apply(ContentIngestionJob.scala:17)
   at content.parquet.ContentIngestionJob$$anonfun$reingest$1$$anonfun$apply$mcV$sp$1.apply(ContentIngestionJob.scala:16)
   at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
   at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
   at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
   at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
   at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
   at org.apache.spark.scheduler.Task.run(Task.scala:121)
   at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
   at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
   at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:748)

**Comment by magro** [comment]
Does this happen with 2.2.0 as well?

Which solrj version(s) do you have in the classpath?

**Comment by AceHack** [comment]
Yes, it does, also pretend I'm completely new to java and gradle so I don't really know what you are talking about classpath.

**Comment by AceHack** [comment]
If it helps I'm using gradle and I'm not overriding the default that comes with solrs.  I'm pulling in whatever version it's pulling in.

**Comment by AceHack** [comment]
So it looks like this starts happening with solr-solrj 7.5.0 and above, it works fine with solr-solrj 7.4.0 and below.  Any chance for an update?  Thanks.

**Comment by magro** [comment]
Do you want to submit a PR? :-)

**Comment by AceHack** [comment]
@magro okay, should I fork, what process would you like me to follow for pull request.

**Comment by AceHack** [comment]
I created a pull request https://github.com/inoio/solrs/pull/63

**Comment by AceHack** [comment]
Finally a good build, please let me know if you would like me to change anything.  I would really like to get this out soon if possible.  Thanks for all your help.

**Comment by magro** [comment]
Closed with c6c9144
